### ISSUE TITLE
Connection closed when we detect nothing

### ISSUE THREAD

**Issue by thorbenortmann** [Sjiun/Tiltometer#10]
When no face (or no speech) is detected, we just return None. This leads to closing the websocket connection after a while. We should rather send a keep connection alive than just None or Nothing. 

Todos for me:
- Add exact reproduction steps
- when fixing this, take learnings from here  https://github.com/affective-reality-group/facial-expression-recognition-microservice/ about docker (and fer) setup.

**Comment by Sjiun** [comment]
Connections may break at "random" on either side for a variety of reasons. 
One [common](https://www.npmjs.com/package/ws#how-to-detect-and-close-broken-connections) way to account for breaking connections is by initiating ping-pong messages every now and again from both server and client sides.

(In addition to not sending empty messages), both server and clients should close any unresponsive connections upon detection. 
Clients should try to establish a new connection. 
If server gets a connection request for a type of client it already has a connection for then it should close the previous connection and accept the new one (?)

**Comment by thorbenortmann** [comment]
Could not reproduce the described issue during my work on #13 and #14 . I would close this issue for now, but keep an eye on it in the future.
